{{- if .Values.apiServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "multiclusterIngress.name" . | trunc 40 }}-api-server"
  labels:
    {{- with .Values.apiServer.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "multiclusterIngress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiServer.replicas }}
  selector:
    matchLabels:
      {{- with .Values.apiServer.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- include "multiclusterIngress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.apiServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "multiclusterIngress.labels" . | nindent 8 }}
        {{- with .Values.apiServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ .Values.apiServer.serviceAccount.name }}"
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.apiServer.podSecurityContext | nindent 8 }}
      containers:
      - name: api-server
        args:
        - --front-end
        envFrom:
        - configMapRef:
            name: mcingress
        - secretRef:
            name: mcingress
        securityContext:
          {{- toYaml .Values.apiServer.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            path: /Healthz/Liveness
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /Healthz/Ready
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.apiServer.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /app/appsettings.json
          subPath: appsettings.json
          name: appconfig
        {{ with .Values.apiServer.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: appconfig
        configMap:
          name: mcingress-appsettings
          items:
          - key: appsettings
            path: appsettings.json
      {{ with .Values.apiServer.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

      {{- with .Values.apiServer.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 6 }}
      {{- end }}

      {{- with .Values.apiServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.apiServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
