{{- if and .Values.apiServer.enabled .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-server
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - multicluster.veccsolutions.io
  verbs:
  - '*'
  resources:
  - clustercaches
  - hostnamecaches
  - resourcecaches
{{- end }}