{{- if .Values.apiServer.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "multiclusterIngress.name" . | trunc 40 }}-api-server"
  labels:
    {{- include "multiclusterIngress.labels" . | nindent 4 }}
    {{- with .Values.apiServer.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.apiServer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.apiServer.ingress.className }}
  {{- if .Values.apiServer.ingress.tls }}
  tls:
    {{- range .Values.apiServer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.apiServer.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: "{{ include "multiclusterIngress.name" $ | trunc 40 }}-api-server"
                port:
                  number: {{ $.Values.apiServer.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
