apiVersion: v1
kind: Service
metadata:
  {{- if .Values.apiServer.service.annotations }}
  annotations:
    {{- toYaml .Values.apiServer.service.annotations | nindent 4 }}
  {{- end }}
  name: "{{ include "multiclusterIngress.name" . | trunc 40 }}-api-server"
  labels:
    {{- with .Values.apiServer.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
  - port: {{ .Values.apiServer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "multiclusterIngress.selectorLabels" . | nindent 4 }}
    {{- with .Values.apiServer.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
