{{- if and .Values.apiServer.enabled .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-server
subjects:
- kind: ServiceAccount
  name: {{ .Values.apiServer.serviceAccount.name }}
{{- end }}
