{{- if .Values.crds.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustercaches.multicluster.veccsolutions.io
spec:
  group: multicluster.veccsolutions.io
  names:
    kind: ClusterCache
    listKind: ClusterCacheList
    plural: clustercaches
    singular: clustercache
  scope: Namespaced
  versions:
  - name: v1alpha
    schema:
      openAPIV3Schema:
        properties:
          lastHeartbeat:
            type: string
          hostnames:
            items:
              properties:
                hostname:
                  type: string
                hostIPs:
                  items:
                    properties:
                      ipAddress:
                        type: string
                      priority:
                        format: int32
                        type: integer
                      weight:
                        format: int32
                        type: integer
                      clusterIdentifier:
                        type: string
                    type: object
                  type: array
              type: object
            type: array
          serviceEndpointCounts:
            items:
              properties:
                namespace:
                  type: string
                service:
                  type: string
                count:
                  format: int32
                  type: integer
              type: object
            type: array
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gslbs.multicluster.veccsolutions.io
spec:
  group: multicluster.veccsolutions.io
  names:
    kind: GSLB
    listKind: GSLBList
    plural: gslbs
    singular: gslb
  scope: Namespaced
  versions:
  - name: v1alpha
    schema:
      openAPIV3Schema:
        description: GSLB object to expose services or ingresses across clusters
        properties:
          objectReference:
            description: Reference to the ingress or service
            properties:
              name:
                minLength: 1
                type: string
              kind:
                enum:
                - Ingress
                - Service
                type: string
            required:
            - name
            - kind
            type: object
          hostnames:
            description: Hostnames to expose the ingress or service as
            items:
              type: string
            type: array
          ipOverrides:
            description: External IP to return instead of what is in the ingress or service
            items:
              type: string
            nullable: true
            type: array
          priority:
            description: Priority to assign this GSLB object. Highest priority is chosen first.
            format: int32
            minimum: 0.0
            type: integer
          weight:
            description: Weight to assign this GSLB object when doing round robin load balancing type. Defaults to 50. The calculation to determine the final weighting of all objects is (weight / sum of all weights) * 100.
            format: int32
            minimum: 0.0
            type: integer
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hostnamecaches.multicluster.veccsolutions.io
spec:
  group: multicluster.veccsolutions.io
  names:
    kind: HostnameCache
    listKind: HostnameCacheList
    plural: hostnamecaches
    singular: hostnamecache
  scope: Namespaced
  versions:
  - name: v1alpha
    schema:
      openAPIV3Schema:
        properties:
          addresses:
            items:
              properties:
                ipAddress:
                  type: string
                priority:
                  format: int32
                  type: integer
                weight:
                  format: int32
                  type: integer
                clusterIdentifier:
                  type: string
              type: object
            type: array
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcecaches.multicluster.veccsolutions.io
spec:
  group: multicluster.veccsolutions.io
  names:
    kind: ResourceCache
    listKind: ResourceCacheList
    plural: resourcecaches
    singular: resourcecache
  scope: Namespaced
  versions:
  - name: v1alpha
    schema:
      openAPIV3Schema:
        properties:
          currentResourceVersion:
            type: string
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicecaches.multicluster.veccsolutions.io
spec:
  group: multicluster.veccsolutions.io
  names:
    kind: ServiceCache
    listKind: ServiceCacheList
    plural: servicecaches
    singular: servicecache
  scope: Namespaced
  versions:
  - name: v1alpha
    schema:
      openAPIV3Schema:
        properties:
          service:
            properties:
              apiVersion:
                type: string
              fieldPath:
                type: string
              kind:
                type: string
              name:
                type: string
              namespace:
                type: string
              resourceVersion:
                type: string
              uid:
                type: string
            type: object
          endpointCount:
            format: int32
            type: integer
        type: object
    served: true
    storage: true
{{- end }}
