apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.orchestrator.serviceAccount.name }}"
  labels:
    {{- include "multiclusterIngress.labels" . | nindent 4 }}
    {{- with .Values.orchestrator.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.orchestrator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
