{{- if and .Values.orchestrator.enabled .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestrator
subjects:
- kind: ServiceAccount
  name: "{{ .Values.orchestrator.serviceAccount.name }}"
{{- end }}
