{{- if and .Values.orchestrator.enabled .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - multicluster.veccsolutions.io
  verbs:
  - '*'
  resources:
  - clustercaches
  - hostnamecaches
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
{{- end }}