{{- if .Values.config.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mcingress
type: Opaque
data:
  {{- if (lookup "v1" "Secret" .Release.Namespace "mcingress").data }}
  ClusterSalt: {{ (lookup "v1" "Secret" .Release.Namespace "mcingress").data.ClusterSalt }}
  {{ else }}
  ClusterSalt: {{ randAscii 64 | b64enc | b64enc }}
  {{ end }}

  {{- range $index, $remote := .Values.config.apiKeys }}
  Authentication__ApiKeys__{{ $index}}__Key: {{ $remote.Key | b64enc }}
  {{- end }}

  {{- range $index, $peer := .Values.config.peers }}
  Peers__{{ $index }}__Key: {{ $peer.Key | b64enc }}
  {{- end }}
{{- end }}
