name: Create Release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.x'

    - name: Run gitversion
      uses: gittools/actions/gitversion/execute@v3.0.0
      id: gitversion

    # - name: Create release
    #   run: gh release create "${{ steps.gitversion.outputs.fullSemVer }}" -t "${{ steps.gitversion.outputs.fullSemVer }}" --generate-notes 
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     INPUT_TAG: ${{ steps.gitversion.outputs.tag }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get quay.io credentials
      run: |
        USERNAME=$(az keyvault secret show --name quay-username --vault-name my-vault --query value -o tsv)
        PASSWORD=$(az keyvault secret show --name quay-password --vault-name my-vault --query value -o tsv)

        echo "DOCKER_USERNAME=$USERNAME" >> $GITHUB_ENV
        echo "DOCKER_PASSWORD=$PASSWORD" >> $GITHUB_ENV

        echo "::add-mask::$USERNAME"
        echo "::add-mask::$PASSWORD"

    - name: Docker login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    
    - name: Test output tags
      run: |
        echo "${{ steps.gitversion.outputs.fullSemVer }}"
        echo "${{ github.ref == 'refs/heads/main' && ('type=semver,pattern={{major}}.{{minor}},value=' + steps.gitversion.outputs.fullSemVer) }}"

    # - name: Docker meta
    #   id: meta
    #   uses: docker/metadata-action@v5
    #   with:
    #     # list of Docker images to use as base name for tags
    #     images: |
    #       quay.io/edward_cooke/vecc.k8s.multiclusteringress
    #     # generate Docker tags based on the following events/attributes
    #     tags: |
    #       type=semver,pattern={{raw}},value=${{ steps.gitversion.outputs.fullSemVer }}
    #       ${{ github.ref == 'refs/heads/main' && 'type=semver,pattern={{major}}.{{minor},value=${{ steps.gitversion.outputs.fullSemVer }}
    #       type=semver,pattern={{major}},value=${{ steps.gitversion.outputs.fullSemVer }}

    # - name: Build Docker image
    #   run: |
    #     docker build -t quay.io/edward_cooke/vecc.k8s.multiclusteringress:latest \
    #                  -t quay.io/edward_cooke/vecc.k8s.multiclusteringress:${{ steps.gitversion.outputs.fullSemVer }} .
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}