name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run tests.sh
      run: ./test.sh
      working-directory: test
      env:
        IS_CI: "1"
    - uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: test/results-*.tgz
